# This is a global registry for public HSDP services
# containing most static configuration. Its main purpose is to
# reduce configuration parameters and drive automation of the
# platform further by having a human and machine readable source of
# common configuration parameters
#
# Before using it as your source of truth please confirm it has
# the expected values.
#
# Also it goes without saying, but we will say it anyway:
# It is your responsibility to ensure correct configuration of
# your deployments.
#
# If you spot errors or incomplete information please raise a
# PR. Thanks!
#
# Definitions:
#
# Region - a geographical region where services are deployed
# Environment - a stage within a geographical region to aid in phased deployment
# Service - a consumable software service
# Instance - a specific deployment of a service
#
# Hierarchy example:
#
# Earth
#   Region us-east
#     Service
#       cf
#     Environment client-test
#       Service
#         iam
#	  idm
#         cartel
#     Environment production
#       Service
#         iam
#         idm
#         cartel
#         cdr
#
#   Region eu-west
#     Environment client-test
#       Service
#         iam
#         idm
#         has
#     Environment production
#       Service
#         iam
#         idm
#         s3cred
#
# Nesting syntax: [region.environment.service.instance]
#
# Services can be tied to a region or an environment
# We also anticipate global services at some point
# Example of a region bound service: Cloud foundry
# Example of a environment bound service: IAM

# Service Cloud foundry
[region.us-east.service.cf]
url = "https://api.cloud.pcftest.com"
domain = "us-east.philips-healthsuite.com"
[region.eu-west.service.cf]
url = "https://api.eu1.phsdp.com"
domain = "eu-west.philips-healthsuite.com"
[region.sa1.service.cf]
url = "https://api.sys.sa1.hsdp.io"
domain = "sa1.hsdp.io"
[region.apac3.service.cf]
url = "https://api.sys.ap3.hsdp.io"
domain = "ap3.hsdp.io"
[region.ca1.service.cf]
url = "https://api.sys.ca1.hsdp.io"
domain = "ca1.hsdp.io"
[region.apac2.service.cf]
url = "https://api.ap-ne.philips-healthsuite.com"

# Service DOCKER-REGISTRY
[region.us-east.service.docker-registry]
url = "https://console.na1.hsdp.io/api/docker/graphql"
host = "docker.na1.hsdp.io"
[region.eu-west.service.docker-registry]
url = "https://console.eu1.hsdp.io/api/docker/graphql"
host = "docker.eu1.hsdp.io"
[region.sa1.service.docker-registry]
url = "https://console.sa1.hsdp.io/api/docker/graphql"
host = "docker.sa1.hsdp.io"
[region.apac3.service.docker-registry]
url = "https://console.ap3.hsdp.io/api/docker/graphql"
host = "docker.ap3.hsdp.io"
[region.ca1.service.docker-registry]
url = "https://console.ca1.hsdp.io/api/docker/graphql"
host = "docker.ca1.hsdp.io"
[region.apac2.service.docker-registry]
url = "https://console.ap2.hsdp.io/api/docker/graphql"
host = "docker.ap2.hsdp.io"

# Service CONSOLE
[region.us-east.service.console]
url = "https://console.na1.hsdp.io"
[region.eu-west.service.console]
url = "https://console.eu1.hsdp.io"
[region.sa1.service.console]
url = "https://console.sa1.hsdp.io"
[region.apac3.service.console]
url = "https://console.ap3.hsdp.io"
[region.ca1.service.console]
url = "https://console.ca1.hsdp.io"
[region.apac2.service.console]
url = "https://console.ap2.hsdp.io"

# Service STL
[region.dev.service.stl]
url = "https://console.na3.hsdp.io/api/stl/user/v1/graphql"
domain = "na1.vpn.hsdp.io"
[region.us-east.service.stl]
url = "https://console.na1.hsdp.io/api/stl/user/v1/graphql"
domain = "na1.vpn.hsdp.io"
[region.eu-west.service.stl]
url = "https://console.eu1.hsdp.io/api/stl/user/v1/graphql"
domain = "emea1.vpn.hsdp.io"

# Service UAA
[region.us-east.service.uaa]
url = "https://uaa.cloud.pcftest.com"
[region.eu-west.service.uaa]
url = "https://uaa.eu1.phsdp.com"
[region.sa1.service.uaa]
url = "https://uaa.sys.sa1.hsdp.io"
[region.apac3.service.uaa]
url = "https://uaa.sys.ap3.hsdp.io"
[region.dev.service.uaa]
url = "https://uaa.cloud.phsdp.com"
[region.ca1.service.uaa]
url = "https://uaa.sys.ca1.hsdp.io"
[region.apac2.service.uaa]
url = "https://uaa.ap-ne.philips-healthsuite.com"

# Notification
[region.us-east.env.client-test.service.notification]
url = "https://notification-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.notification]
url = "https://notification-service.us-east.philips-healthsuite.com"
[region.us-east.env.dev.service.notification]
url = "https://notification-dev.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.notification]
url = "https://notification-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.notification]
url = "https://notification-service.eu-west.philips-healthsuite.com"
[region.sa1.env.prod.service.notification]
url = "https://notification-service.sa1.hsdp.io"
[region.cn1.env.prod.service.notification]
url = "https://notification-service.cn1.philips-healthsuite.com.cn"
[region.apac3.env.prod.service.notification]
url = "https://notification-service.ap3.hsdp.io"
[region.ca1.env.prod.service.notification]
url = "https://notification-service.ca1.hsdp.io"

# Service IAM
[region.us-east.env.client-test.service.iam]
url = "https://iam-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.iam]
url = "https://iam-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.iam]
url = "https://iam-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.iam]
url = "https://iam-service.eu-west.philips-healthsuite.com"
[region.sa1.env.prod.service.iam]
url = "https://iam-service.sa1.hsdp.io"
[region.apac3.env.prod.service.iam]
url = "https://iam-service.ap3.hsdp.io"
[region.us-east.env.dev.service.iam]
url = "https://iam-development.us-east.philips-healthsuite.com"
[region.cn1.env.prod.service.iam]
url = "https://iam-service.cn1.philips-healthsuite.com.cn"
[region.ca1.env.prod.service.iam]
url = "https://iam-service.ca1.hsdp.io"

# Service IDM
[region.us-east.env.client-test.service.idm]
url = "https://idm-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.idm]
url = "https://idm-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.idm]
url = "https://idm-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.idm]
url = "https://idm-service.eu-west.philips-healthsuite.com"
[region.sa1.env.prod.service.idm]
url = "https://idm-service.sa1.hsdp.io"
[region.apac3.env.prod.service.idm]
url = "https://idm-service.ap3.hsdp.io"
[region.us-east.env.dev.service.idm]
url = "https://idm-development.us-east.philips-healthsuite.com"
[region.cn1.env.prod.service.idm]
url = "https://idm-service.cn1.philips-healthsuite.com.cn"
[region.ca1.env.prod.service.idm]
url = "https://idm-service.ca1.hsdp.io"

# Service CARTEL
[region.dev.service.cartel]
host = "cartel-na1.cloud.phsdp.com"
[region.us-east.service.cartel]
host = "cartel-na1.cloud.phsdp.com"
[region.eu-west.service.cartel]
host = "cartel-eu1.cloud.phsdp.com"
[region.sa1.service.cartel]
host = "cartel-sa1.cloud.phsdp.com"
[region.ca1.service.cartel]
host = "cartel-ca1.cloud.phsdp.com"
[region.apac2.service.cartel]
host = "cartel-apac2.cloud.phsdp.com"
[region.apac3.service.cartel]
host = "cartel-apac3.cloud.phsdp.com"

# Service GATEWAY
[region.dev.service.gateway]
host = "gw-na1.phsdp.com"
domain = "na1.phsdp.com"
[region.us-east.service.gateway]
host = "gw-na1.phsdp.com"
domain = "na1.phsdp.com"
[region.eu-west.service.gateway]
host = "gw-eu1.phsdp.com"
domain = "emea1.phsdp.com"
[region.sa1.service.gateway]
host = "gw-sa1.phsdp.com"
domain = "sa1.phsdp.com"
[region.apac3.service.gateway]
host = "gw-apac3.phsdp.com"
domain = "apac3.phsdp.com"
[region.ca1.service.gateway]
host = "gw-ca1.phsdp.com"
domain = "ca1.phsdp.com"
[region.apac2.service.gateway]
host = "gw-apac2.phsdp.com"
domain = "apac2.phsdp.com"

# Service S3CREDS
[region.us-east.env.dev.service.s3creds]
url = "https://s3creds-development.us-east.philips-healthsuite.com"
[region.us-east.env.client-test.service.s3creds]
url = "https://s3creds-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.s3creds]
url = "https://s3creds-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.s3creds]
url = "https://s3creds-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.s3creds]
url = "https://s3creds-service.eu-west.philips-healthsuite.com"
[region.apac3.prod.service.s3creds]
url = "https://s3creds-service.ap3.hsdp.io"
[region.cn1.env.prod.service.s3creds]
url = "https://s3creds-service.cn1.philips-healthsuite.com.cn"

# Service HAS
[region.eu-west.env.client-test.service.has]
url = "https://has-client-test.eu-west.philips-healthsuite.com"

# Service CDR-STU3
[region.us-east.env.sandbox.service.cdr-stu3]
url = "https://cdr-stu3-sandbox.us-east.philips-healthsuite.com"

# Service LOGGING
[region.eu-west.env.client-test.service.logging]
url = "https://logingestor2-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.logging]
url = "https://logingestor2.eu-west.philips-healthsuite.com"
[region.us-east.env.client-test.service.logging]
url = "https://logingestor2-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.logging]
url = "https://logingestor2.us-east.philips-healthsuite.com"
[region.sa1.env.prod.service.logging]
url = "https://logingestor2.sa1.hsdp.io"
[region.apac3.env.prod.service.logging]
url = "https://logingestor2.ap3.hsdp.io"
[region.ca1.env.prod.service.logging]
url = "https://logingestor2.ca1.hsdp.io"

# Service LOGQUERY
[region.eu-west.env.client-test.service.logquery]
url = "https://logquery-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.logquery]
url = "https://logquery.eu-west.philips-healthsuite.com"
[region.us-east.env.client-test.service.logquery]
url = "https://logquery-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.logquery]
url = "https://logquery.us-east.philips-healthsuite.com"
[region.sa1.env.prod.service.logquery]
url = "https://logquery.sa1.hsdp.io"
[region.apac3.env.prod.service.logquery]
url = "https://logquery.ap3.hsdp.io"
[region.ca1.env.prod.service.logquery]
url = "https://logquery.ca1.hsdp.io"

# Service KIBANA
[region.eu-west.env.client-test.service.kibana]
url = "https://kibana-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.kibana]
url = "https://kibana.eu-west.philips-healthsuite.com"
[region.us-east.env.client-test.service.kibana]
url = "https://kibana-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.kibana]
url = "https://kibana.us-east.philips-healthsuite.com"
[region.sa1.env.client-test.service.kibana]
url = "https://kibana-client-test.sa1.hsdp.io"
[region.sa1.env.prod.service.kibana]
url = "https://kibana.sa1.hsdp.io"
[region.apac3.env.prod.service.kibana]
url = "https://kibana.ap3.hsdp.io"
[region.ca1.env.prod.service.kibana]
url = "https://kibana.ca1.hsdp.io"

# Service PKI
[region.eu-west.env.client-test.service.pki]
url = "https://pki-proxy-client-test.eu-west.philips-healthsuite.com"
[region.us-east.env.client-test.service.pki]
url = "https://pki-client-test.us-east.philips-healthsuite.com"

# Service VAULT-PROXY
[region.us-east.service.vault-proxy]
url = "https://vproxy.us-east.philips-healthsuite.com"
[region.us-west.service.vault-proxy]
url = "https://vproxy.cloud.phsdp.com"
[region.eu-west.service.vault-proxy]
url = "https://vproxy.eu-west.philips-healthsuite.com"
[region.sa1.service.vault-proxy]
url = "https://vproxy.sa1.hsdp.io"
[region.apac3.service.vault-proxy]
url = "https://vproxy.ap3.hsdp.io"
[region.cn1.service.vault-proxy]
url = "https://vproxy.cn1.philips-healthsuite.com.cn"
[region.ca1.service.vault-proxy]
url = "https://vproxy.ca1.hsdp.io"

# Service INFERENCE
[region.us-east.env.client-test.service.inference]
url = "https://client-test-aiinference-service.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.inference]
url = "https://aiinference-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.inference]
url = "https://client-test-aiinference-service.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.inference]
url = "https://aiinference-service.eu-west.philips-healthsuite.com"

# Service WORKSPACE
[region.us-east.env.client-test.service.workspace]
url = "https://client-test-aiworkspace-service.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.workspace]
url = "https://aiworkspace-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.workspace]
url = "https://client-test-aiworkspace-service.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.workspace]
url = "https://aiworkspace-service.eu-west.philips-healthsuite.com"

# Service TRAINING
[region.us-east.env.client-test.service.training]
url = "https://client-test-training-service.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.training]
url = "https://training-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.training]
url = "https://client-test-training-service.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.training]
url = "https://training-service.eu-west.philips-healthsuite.com"

# Service CONNECT-MDM
[region.us-east.env.client-test.service.connect-mdm]
url = "https://connect-mdm-client-test.us-east.philips-healthsuite.com/connect/mdm"
[region.us-east.env.prod.service.connect-mdm]
url = "https://connect-mdm.us-east.philips-healthsuite.com/connect/mdm"
[region.eu-west.env.client-test.service.connect-mdm]
url = "https://connect-mdm-client-test.eu-west.philips-healthsuite.com/connect/mdm"
[region.eu-west.env.prod.service.connect-mdm]
url = "https://connect-mdm.eu-west.philips-healthsuite.com/connect/mdm"

# Service DISCOVERY
[region.us-east.env.client-test.service.discovery]
url = "https://discovery-client-test.us01.connect.hsdp.io/client-test/core/discovery"
[region.eu-west.env.client-test.service.discovery]
url = "https://discovery-client-test.eu01.connect.hsdp.io/client-test/core/discovery"

# Service BLR
[region.us-east.env.client-test.service.blr]
url = "https://blobrepository-client-test.us01.connect.hsdp.io/connect/blobrepository"
[region.eu-west.env.prod.service.blr]
url = "https://blobrepository-client-test.eu01.connect.hsdp.io/connect/blobrepository"
[region.cn1.prod.service.blr]
url = "https://blobrepository.cn1.iot.philips-healthsuite.com.cn/connect/blobrepository"

# Service IOT
[region.us-east.env.client-test.service.iot]
url = "wss://a2vgioynsisd7n-ats.iot.us-east-1.amazonaws.com/mqtt?topic-prefix=client-test"
[region.eu-west.env.prod.service.iot]
url = "wss://a370yzaa002yx5-ats.iot.eu-west-1.amazonaws.com/mqtt?topic-prefix=prod"
[region.cn1.prod.service.iot]
url = "wss://aqrsmt9m297sm.ats.iot.cn-north-1.amazonaws.com.cn/mqtt?topic-prefix=prod"
